id = "iris"
name = "Iris Language Support"
version = "0.1.0"
schema_version = 1
description = "Syntax highlighting and editor support for IRIS (.iris) files."
repository = "https://github.com/ljack/iris-v0"
authors = ["Iris Contributors <dev@iris-lang.org>"]

[grammars.iris]
repository = "file:///Users/jarkko/_dev/iris-v0/.git"
rev = "aa8b0445e6d663852e698ed79c6134ea3c32794f"
path = "tree-sitter-iris"

[language_servers.iris-lsp]
name = "IRIS Language Server"
language = "iris"

[context_servers]

[agent_servers]

[slash_commands]
