id = "iris"
name = "Iris Language Support"
version = "0.1.0"
schema_version = 1
description = "Syntax highlighting and editor support for IRIS (.iris) files."
repository = "https://github.com/ljack/iris-v0"
authors = ["Iris Contributors <dev@iris-lang.org>"]

[grammars.iris]
repository = "file:///Users/jarkko/_dev/iris-v0/.git"
rev = "98805a6806912099b58b463766414763b343ab3c"
path = "tree-sitter-iris"

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
